[package]
name = "saes-gbot"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
dotenvy = "0.15.7"
gcp_auth = "0.12.3"
google-sheets4 = "6.0.0"
reqwest = "0.12.12"
serde = "1.0.217"
serde_json = "1.0.135"
tokio = { version = "1.43.0", features = ["full"] }
