[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
serde = { version = "1.0.198", features = ["derive"] }
sea-orm = { version = "0.12.15", features = ["sqlx-mysql", "runtime-tokio-native-tls", "macros"] }
serde_json = "1.0.116"
ezoauth = "0.2.0"
axum = "0.7.5"
tokio = { version = "1.37.0", features = ["full"] }
